model:
  type: pdc
  checkpoint:
    path:  ./trained_models/29000.pt
    type: ProbabilityDensityCloud
  encoder:
    node_feat_dim: 128
    pair_feat_dim: 64
    num_layers: 3
    refine_num_layers: 1
    num_nearest_neighbors: 8
    norm_coors: True
    update_coors_mean: True   # update mean
    update_coors_var: True
    learnable_var: True
  pos:
    recycle: 1
    mask_length: 5
    mask_noise_scale: 0.5
    mask_wt: True
  use_plm: False
  resolution: backbone+CB

data:
  reset: False
  skempi_csv_path: ./data/SKEMPI_v2/skempi_v2.csv
  skempi_pdb_dir: ./data/SKEMPI_v2/PDBs
  cache_dir: ./data/SKEMPI_v2_cache
  transform:
  - type: select_atom
    resolution: backbone+CB
  - type: selected_region_fixed_size_patch
    select_attr: mut_flag
    patch_size: 128   # default 128

train:
  loss_weights:
    pos_refine: 1.0
    regression: 1.0
  max_iters: 100_000
  val_freq: 1000
  batch_size: 64    # default 32
  seed: 2023
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 3.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 5
    min_lr: 1.e-6
