model:
  encoder:
    node_feat_dim: 128
    pair_feat_dim: 64
    num_layers: 6
  flow:
    num_blocks: 8
    num_hidden_dims: 128
    num_spline_bins: 64

data:
  type: pdbredo_chain
  pdbredo_dir: /nfs_beijing/linlinchao/git/RDE-PPI/data/PDB_REDO
  clusters_path: /nfs_beijing/linlinchao/git/RDE-PPI/data/pdbredo_clusters.txt
  splits_path: /nfs_beijing/linlinchao/git/RDE-PPI/data/pdbredo_splits.txt
  processed_dir: ./data/PDB_REDO_processed_raw
  #cache_dir: /nfs_beijing/linlinchao/git/RDE-PPI/data/PDB_REDO_processed_raw
  transform: # TODO: combine train.yml and val.yml
    ## Only backbone atoms and CB are visible to rotamer predictor
    - type: select_atom
      resolution: backbone+CB
    - type: focused_random_patch
      focus_attr: focus_flag   # a randomly selected chain
      seed_nbh_size: 32
      patch_size: 128
    - type: corrupt_chi_angle
      ratio_mask: 0.4
      maskable_flag_attr: focus_flag

train:
  loss_weights:
    mle_1chis: 0.25
    mle_2chis: 0.25
    mle_3chis: 0.25
    mle_4chis: 0.25
  max_iters: 200_000
  val_freq: 1000
  batch_size: 64
  seed: 2022
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 5
    min_lr: 1.e-6
